### ISSUE TITLE
query lock list via Google Query from Google Sheets?

### ISSUE THREAD

**Issue by davidem00** [noke-inc/noke-core-api-documentation#2]
is there a way to do this from directly within Google Sheets, or perhaps via a user-contributed script?

For the time being I would just like to query my lock list and present it in a nice way to some of my internal members without them needing to login to the management portal.

**Comment by pantsmann** [comment]
If you are using CoreAPI then the /lock/ endpoint will list locks for you. If you are using a different Noke product, such as Noke Pro, CoreAPI will not help you.
